### ISSUE TITLE
Use Type

### ISSUE THREAD

**Issue by iammarkps** [programming-in-th/programming.in.th#157]
We are using TypeScript, but some type is missing from our code. Need FIX

**Comment by pontakornth** [comment]
Could you provide more description,please?

**Comment by iammarkps** [comment]
@pontakornth In our code some of type is still any.

**Comment by rayriffy** [comment]
I'll try

**Comment by iammarkps** [comment]
@pontakornth As @rayriffy said, He can't track the missing type. So I'm thinking about reading all the code and find "any" type and fix that.
