### ISSUE TITLE
Need refactoring and better code architecture

### ISSUE THREAD

**Issue by iammarkps** [programming-in-th/programming.in.th#158]

**Comment by alessandrojcm** [comment]
Please elaborate.

**Comment by rayriffy** [comment]
Check my new code architecture at my repo (https://github.com/rayriffy/rayriffy-h)

Here's the rules of my structure please look at my repo along with reading this rule

- Each feature will be completely separate into it's own directory which each directory will includes
  - `@types/` is being used for storing **TypeScript Types**
  - `components/` is being used for storing UI of it's feature
  - `services/` is being used for storing **all functions** that being used by feature
  - `context/` and `reducer/` is optionally included for storing **Context API** and **Reducer**

- Directories are separate by it's own definition
  - `app/` directory is using for rendering app shell
  - `core/` directory is being used with component/functions that **can be reused in many features**
  - `pages/` directory is for storing each feature which will be only used once (single page etc.)
  - `templates/` directory is for storing feature that will going to be used many times (dynamic urls etc.)

**Comment by iammarkps** [comment]
@alessandrojcm Some code in this repo is still messy and un-structured. So I'm thinking about enforcing code stucture and refactor the old code.

**Comment by alessandrojcm** [comment]
@iammarkps Sure I'll get that, but, do you have some code structure in mind I should follow? Or the one pointed by @rayriffy it's ok? (I personally think it's ok, I myself structure my code very similar to that). And also, what part of the code you think is messy? So I can use that as a starting point.

**Comment by iammarkps** [comment]
@alessandrojcm Yes! I'm ok with @rayriffy code structure.

**Comment by alessandrojcm** [comment]
@iammarkps Cool, I'll get to work then.

**Comment by alessandrojcm** [comment]
BTW you should merge the PRs from the dependabot.
