### ISSUE TITLE
Feature Request : Auto-refresh submission

### ISSUE THREAD

**Issue by vzsky** [programming-in-th/programming.in.th#162]
**Feature request**
Use some web-sockets emitting events to notify users their submission results.
Add some loading animations too ! >.<

an example : [CodeForce](https://codeforces.com)

**Comment by iammarkps** [comment]
Notifications have been enabled, but the SubmissionDetails component still has a bug with auto-refreshing.

**Comment by iammarkps** [comment]
Done
