### ISSUE TITLE
Improve User Interface (Bugs)

### ISSUE THREAD

**Issue by chunza2542** [programming-in-th/programming.in.th#163]
- Thai-font is too small to read.
- Have too much margin on the container (on small-width device)
- Pagination Layout bugs on mobile.
- Problem PDF is too small to read on mobile.
- Maybe add more white-space on text can make UI better and clean.

**Comment by chunza2542** [comment]
Can you please assign this task to me? I'll send you PR later.

**Comment by iammarkps** [comment]
I will assign you to this issue! Thank you for your contribution in advance

**Comment by iammarkps** [comment]
Done in #176
