### ISSUE TITLE
Redux devtools should be disable on production?

### ISSUE THREAD

**Issue by MicroBenz** [programming-in-th/programming.in.th#165]
Should we disable redux-devtools on the production site?

![image](https://user-images.githubusercontent.com/9103800/66303505-56c00f80-e925-11e9-9e9a-0dd33345975b.png)

**Comment by iammarkps** [comment]
I've done some research and upon consultation with my colleagues, we've agreed to enable Redux DevTools in production. [This](https://medium.com/@zalmoxis/using-redux-devtools-in-production-4c5b56c5600f) article seems to indicate that the benefits of enabling Redux DevTools outweigh its costs. If you have differing opinions, feel free to let us know.

**Comment by MicroBenz** [comment]
I've read an article. My opinion is if the site didn't contain any sensitive information it should be fine.

So I'm closing and issue na kub :)
