### ISSUE TITLE
bugs on UI and features request

### ISSUE THREAD

**Issue by vzsky** [programming-in-th/programming.in.th#178]
- Hide code on the submission pages doesn't work.
- auto select language when upload a code
- remove cursor from the code in submission detail

**Comment by iammarkps** [comment]
You still can see your own code while you choose to hide it. But others can't

**Comment by iammarkps** [comment]
For "auto select language when upload a code", I think it can't be implemented. Because you still can type C++ code in .py extension and upload it as C++ code. So you don't really know what language user is writing in.
