### ISSUE TITLE
Suggestion: Checklist connected to submission

### ISSUE THREAD

**Issue by Autoratch** [programming-in-th/programming.in.th#189]
Checklist could be divided by category and have summation for each category.

(This way many one will change to use betabeta because they don't have to mark their checklist by themselves)

**Comment by win11905** [comment]
โยนงานอยู่ได้ไอสัส

**Comment by iammarkps** [comment]
We added a bookmark and completion system on `next` branch already. So this feature will be available after we ship v1.0.0
