### ISSUE TITLE
Developer chatroom.

### ISSUE THREAD

**Issue by wizzup** [programming-in-th/programming.in.th#201]
What is the status of project? It look very much active recently.

How do you guys communicate?  https://gitter.im/ is a good choice.

The old [forum](https://programming.in.th/forum/index.php) seem inactive and contains lots of spams.

**Comment by iammarkps** [comment]
Hi!, we are migrating to NextJS right now. So our master branch is currently stale. If you want to see our current progress you can see at next branch
