### ISSUE TITLE
Ability to hide submission from others

### ISSUE THREAD

**Issue by PeppaPigHS** [programming-in-th/programming.in.th#447]
Users should have permission to enable and disable others' ability to view their submissions. Otherwise, make all submissions private.

**Comment by win11905** [comment]
@iammarkps @szawinis What do you think about it? I think users shouldn't have permission to hide submissions.

**Comment by win11905** [comment]
@PeppaPigHS please explain why I should add this feature.

**Comment by PeppaPigHS** [comment]
I think submission is user's private property, and it shouldn't be publicly displayed without user's consent

**Comment by win11905** [comment]
Codeforces, oj.uz, and AtCoder are public their user's submissions and every user approves the website to public their submissions. I think programming.in.th should use the same model as these websites.

**Comment by PeppaPigHS** [comment]
What is the main reason to follow the model? As there are some websites that also hide user's submission as well, like DMOJ, USACO, dunjude, wcipeg and SPOJ

**Comment by win11905** [comment]
The purpose of hiding submissions is users should solve tasks without solutions but programming.in.th will have solutions page which everyone can view without any condition. It isn't necessary to hide their submissions.
