### ISSUE TITLE
Right click on taskList and submissonList table

### ISSUE THREAD

**Issue by PeppaPigHS** [programming-in-th/programming.in.th#484]

**Comment by twattanawaroon** [comment]
Items in those tables are not proper <a> so browsers don't allow right-clicking to "Open link in new tab..." for example.
Additionally, because you cannot open pages in a new tab, you open it in the same page, and when you come back to the list, you start at page 1 in the paginated list again.

**Comment by iammarkps** [comment]
I will fix this issue by persisting pagination, because table element is not possible to render with "Open link in new tab..."
