### ISSUE TITLE
Blank Submission Slot in Submission Page

### ISSUE THREAD

**Issue by miello** [programming-in-th/programming.in.th#487]
Blank Submission Slot appears when first time click **Load More** in submission page, this slot can hover but can't click

![Bug](https://user-images.githubusercontent.com/35169079/86201157-f941b200-bb88-11ea-8bad-423268293015.PNG)

**Comment by win11905** [comment]
Hello @miello, it is hidden submission. Due to test case not found in `0006`, I hid this task, and all submissions of this task also hidden.

**Comment by miello** [comment]
I think we should hide the hidden submission without having slot display in submission page, it might look cleaner then having an empty slot remaining

**Comment by win11905** [comment]
@miello this is an issue of the firebase. I can't filter the hidden tasks from the submissions because the boolean collecting `isHide`  is on the tasks' database. Sometimes, the hidden submission is continuous for more than 10 submissions. The load more button doesn't load any submission more.

**Comment by miello** [comment]
Ok we can ignore about it, the task is hidden from task page then it never get the hidden submission unless the past submission. I'm going to close this issue
