### ISSUE TITLE
Use CSS module instead

### ISSUE THREAD

**Issue by iammarkps** [programming-in-th/programming.in.th#76]
https://github.com/css-modules/css-modules

**Comment by win11905** [comment]
I will do it.

**Comment by rayriffy** [comment]
FYI I recommended to use `styled-components` instead of CSS modules
https://www.styled-components.com/

**Comment by win11905** [comment]
Do you have example project that use `styled-components`? @rayriffy

**Comment by rayriffy** [comment]
I have my CV site that use `rebass` and using `styled-component` to extending CSS properties from rebass component itself
https://github.com/rayriffy/rayriffy-cv-next

**Comment by iammarkps** [comment]
Use ant.design and styled-components instead
