### ISSUE TITLE
max username length on submission list 

### ISSUE THREAD

**Issue by Nacnano** [programming-in-th/programming.in.th#791]
**Problem**
There are some cases where the usernames are too long. As a result, the submission list has become longer than usual. Although this is not common, encountering cases like this can cause annoyance to users.

an example video:

https://user-images.githubusercontent.com/59221274/179493225-58cd2df6-b1e6-4973-817f-53aa116bb26d.mp4

**Solution**
The solution I'd like: As the main problem (annoyance) is only caused by the submission page, showing only just maximum string length on the submission page should be enough. 
For example, "12345678901234567890123456789" should be shown as "1234567890...".

Alternate solution: Or just maximize the username when users input their username

Thank you for your consideration

**Comment by iammarkps** [comment]
will fix on `next` branch

**Comment by iammarkps** [comment]
Fixed in https://github.com/programming-in-th/programming.in.th/commit/c6e2fed084196445b0144a13fa145a52121606c6
