### ISSUE TITLE
Missing -lm Compiler Flag for Submissions?

### ISSUE THREAD

**Issue by chalkp** [programming-in-th/programming.in.th#942]
from this submission: https://programming.in.th/submissions/97973
`#include <math.h>`
include error?

im not sure whether this is relevant but from compiler tags i got from this repo :
https://github.com/programming-in-th/rusty-grader/blob/68f78da9d6713ea97a8c86ef517463ffc13e96c6/example/scripts/compile_scripts/c#L13
this code should compile with that tags successfully

**Comment by MasterIceZ** [comment]
Should be fixed by https://github.com/programming-in-th/rusty-grader/pull/25
