### ISSUE TITLE
Meta title missing on all pages.

### ISSUE THREAD

**Issue by gxjakkap** [programming-in-th/programming.in.th#945]
Is this intentional? If not I'm willing to make a pull request to fix it.

![image](https://github.com/programming-in-th/programming.in.th/assets/55027998/76fe9472-b36a-4e18-9e72-09b889b27dd4)

![image](https://github.com/programming-in-th/programming.in.th/assets/55027998/cfd3ad3d-2475-47d8-9c24-08ed1400d183)

**Comment by MasterIceZ** [comment]
We didn't plan to do this, but if you're interested, you can start right away.

**Comment by leomotors** [comment]
Fixed by #946
